version: "3"
services:
  web:
    build:
      context: ./docker/elixir
    working_dir: /src
    volumes:
      - ./src:/src
    # environment:
    #   - "POSTGRES_USER=${POSTGRES_USER}"
    #   - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    #   - "PGDATABASE=${PGDATABASE}"
    #   - "PGPORT=${PGPORT}"
    #   - "PGHOST=${PGHOST}"
    # ports:
    # - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ${PWD}/docker/db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
